apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-5c98"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-5c98"
  template:
    metadata:
      labels:
        app: "myakscluster-5c98"
    spec:
      containers:
        - name: "myakscluster-5c98"
          image: "mycapg2023.azurecr.io/myakscluster"
          ports:
          - containerPort: 8080